apiVersion: v1
kind: Service
metadata:
  name: {{ include "js9fileviewer.fullname" . }}
  labels:
    {{- include "js9fileviewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "js9fileviewer.selectorLabels" . | nindent 4 }}
    app: js9docker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "js9fileviewer.fullname" . -}} - {{- "helper" }}
  labels:
    {{- include "js9fileviewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "js9fileviewer.selectorLabels" . | nindent 4 }}
    app: js9docker
